### ISSUE TITLE
REPL doesn't use configured font

### ISSUE THREAD

**Issue by DjebbZ** [idris-hackers/atom-language-idris#191]
Hello,

First : thank you for the package ! Really nice to learn Idris with the book "Type-Driven development with Idris".

Second : it may be related to #139, but the panel doesn't use the configured font. I'm using Fira Code for the ligatures.

I tried the following in the `Application : open your Stylesheet` (styles.less), with strictly no change :

``` css
.atom-panel {
  font-size: 20px;
  font-family: "Fira Code";
}

.tool-panel {
  font-size: 20px;
  font-family: "Fira Code";
}

.panel-heading {
  font-size: 20px;
  font-family: "Fira Code";
}

.line-message .preview {
  font-size: 20px;
  font-family: "Fira Code";
}
```

Using Atom 1.20.1 on Linux and your plugin v0.4.10.

Feel free to close the ticket if you consider it a duplicate of #139 and/or that I am a "help vampire".
